# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setGeometry(QtCore.QRect(180, 30, 611, 541))
        self.mdiArea.setObjectName("mdiArea")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(0, 30, 181, 541))
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actiondlg1 = QtWidgets.QAction(MainWindow)
        self.actiondlg1.setObjectName("actiondlg1")
        self.actiondlg2 = QtWidgets.QAction(MainWindow)
        self.actiondlg2.setObjectName("actiondlg2")
        self.actionsubwin1 = QtWidgets.QAction(MainWindow)
        self.actionsubwin1.setObjectName("actionsubwin1")
        self.actionsubwin2 = QtWidgets.QAction(MainWindow)
        self.actionsubwin2.setObjectName("actionsubwin2")
        self.menufile.addAction(self.actiondlg1)
        self.menufile.addAction(self.actiondlg2)
        self.menufile.addAction(self.actionsubwin1)
        self.menufile.addAction(self.actionsubwin2)
        self.menubar.addAction(self.menufile.menuAction())
        self.toolBar.addAction(self.actiondlg1)
        self.toolBar.addAction(self.actiondlg2)
        self.toolBar.addAction(self.actionsubwin1)
        self.toolBar.addAction(self.actionsubwin2)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actiondlg1.setText(_translate("MainWindow", "dlg1"))
        self.actiondlg2.setText(_translate("MainWindow", "dlg2"))
        self.actionsubwin1.setText(_translate("MainWindow", "subwin1"))
        self.actionsubwin2.setText(_translate("MainWindow", "subwin2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
