# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stats.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
"""
使用PyQtUic工具将ui转成代码
"""

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(648, 566)
        self.Input = QtWidgets.QPlainTextEdit(Form)
        self.Input.setGeometry(QtCore.QRect(10, 30, 241, 511))
        self.Input.setDocumentTitle("")
        self.Input.setObjectName("Input")
        self.Output = QtWidgets.QPlainTextEdit(Form)
        self.Output.setGeometry(QtCore.QRect(410, 30, 231, 511))
        self.Output.setObjectName("Output")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(264, 280, 121, 31))
        self.pushButton.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "统计薪资"))
        self.Input.setPlaceholderText(_translate("Form", "请输入薪资信息..."))
        self.Output.setPlaceholderText(_translate("Form", "统计结果"))
        self.pushButton.setText(_translate("Form", "统计"))


from PySide2.QtWidgets import QApplication, QMessageBox,QMainWindow
from PySide2.QtUiTools import QUiLoader

class Stats(QMainWindow):
    def __init__(self):
        # 从文件中加载UI定义

        # 从 UI 定义中动态 创建一个相应的窗口对象
        # 注意：里面的控件对象也成为窗口对象的属性了
        # 比如 self.ui.button , self.ui.textEdit
        # self.ui = QUiLoader().load('ui/stats.ui')
        # self.ui = uic.loadUi("ui/stats.ui")

        super().__init__()
        # 使用ui文件导入定义界面类
        self.ui = Ui_Form()
        # 初始化界面
        self.ui.setupUi(self)

        self.ui.pushButton.clicked.connect(self.handleCalc)

    def handleCalc(self):
        info = self.ui.Input.toPlainText()

        salary_above_20k = ''
        salary_below_20k = ''
        for line in info.splitlines():
            if not line.strip():
                continue
            parts = line.split(' ')

            parts = [p for p in parts if p]
            name,salary,age = parts
            if int(salary) >= 20000:
                salary_above_20k += name + '\n'
            else:
                salary_below_20k += name + '\n'

        self.ui.Output.setPlaceholderText(f'''薪资20000 以上的有：\n{salary_above_20k}\n薪资20000 以下的有：\n{salary_below_20k}''')

app = QApplication([])
stats = Stats()
stats.ui.show()
app.exec_()